client/app/home/views.py
"""Home."""
from flask import Blueprint, render_template

home_bp = Blueprint("home", __name__)


@home_bp.route("/")
def home():
    """Home view."""
    return render_template(
        "home.html", title="\\\\barry_v_martin\\\\", title_img="me.jpg"
    )

client/app/project/views.py
import json
import math
import os
from datetime import datetime, timedelta
import pytz
import time

import boto3
# from app import cache
from botocore.exceptions import ClientError
from flask import Blueprint, render_template, make_response, jsonify
from flask_restx import Api, Resource
import psycopg2 as pg2
import pandas as pd
import plotly
import plotly.express as px
import s3fs

project_bp = Blueprint("project", __name__, url_prefix="/project")
api = Api(project_bp)


# def get_data(date):
#     s3 = boto3.resource("s3")
#     try:
#         content_object = s3.Object("artist-followers", f"{date}.json")
#         file_content = content_object.get()["Body"].read().decode("utf-8")
#         return json.loads(file_content)
#     except ClientError:
#         return None


# @project_bp.route("/")
# def project():
#     return render_template(
#         "project.html", title="\\\\sample_project\\\\", title_img="project.png"
#     )

# @project_bp.route("/music")
# def project2():
#     return render_template(
#         "project2.html", title="\\\\sample_project\\\\", title_img="project2.jpg"
#     )


# @api.route("/api/artists/<artist>/weekly")
# class ArtistApi(Resource):
#     @cache.cached(timeout=1000, query_string=True)
#     def get(self, artist):
#         # hard code due to twitter API now chargin
#         start = datetime(2023, 1, 1)
#         end = datetime(2023, 1, 7)
#         data = {}
#         while start <= end:
#             date = start.strftime("%Y%m%d")
#             json_data = get_data(date)
#             if json_data:
#                 data[date] = json_data[artist]
#             start = start + timedelta(days=1)
#         return data

    
class Database:
  def __init__(self):
    self.host = os.getenv("DB_HOST")
    self.db = os.getenv("DB_NAME")
    self.username = os.getenv("DB_USER")
    self.password = os.getenv("DB_PASS")
    self.port = os.getenv("DB_PORT")
    self.cur = None
    self.conn = None

  def get_data(self):
    engine = pg2.connect(f"dbname='{self.db}' user='{self.username}' host='{self.host}' port='{self.port}' password='{self.password}'")
    query = """
            SELECT *
            FROM public.weather
            order by api_datetime desc
            limit 156
            """
    df = pd.read_sql(query, con=engine)
    df["api_datetime"] = df["api_datetime"].dt.tz_localize('UTC').dt.tz_convert('US/Eastern')
    engine.close()
    return df
  
  def get_current_max_temp(self, date):
    engine = pg2.connect(f"dbname='{self.db}' user='{self.username}' host='{self.host}' port='{self.port}' password='{self.password}'")
    query = f"""
            SELECT api_datetime, temp_f
            FROM public.weather
            order by api_datetime desc
            limit 500
            """
    df = pd.read_sql(query, con=engine)
    df["date"] = df["api_datetime"].dt.tz_localize('UTC').dt.tz_convert('US/Eastern')
    engine.close()
    df = df[df['date'].dt.date == date]
    return df.temp_f.max()
  
  def get_latest_temp(self):
    engine = pg2.connect(f"dbname='{self.db}' user='{self.username}' host='{self.host}' port='{self.port}' password='{self.password}'")
    query = """
            SELECT temp_f
            FROM public.weather
            order by api_datetime desc
            limit 1
            """
    df = pd.read_sql(query, con=engine)
    engine.close()
    return df.temp_f.values[0]


def get_wind_direction_string(degrees):
    val = int((degrees/22.5)+.5)
    arr = ["N","NNE","NE","ENE","E","ESE", "SE", "SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"]
    return arr[(val % 16)]

def get_plot(df, field, unit):
    if field == "temperature":
        y = f'temp_{unit}'
    if field == "dew point":
        y = f'dew_point_{unit}'
    if field == "wind":
        y = f'wind_speed_{unit}'
    if field == "pressure":
        y = f'barometric_pressure_{unit}'
    if field == "hourly rain":
        y = f'hourly_rain_{unit}'
    title = f"{field.upper()} {unit.upper()}"
    fig = px.line(df, x='api_datetime', y=y, title=title)
    return json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

def get_current_weather(df):
    df = df.head(1)
    wind_dir = get_wind_direction_string(df.wind_dir.values[0])
    return {
        "Timestamp": df.api_datetime.dt.strftime('%Y-%m-%d %I:%M %p EST').values[0],
        "Temperature": {"F": math.ceil(df.temp_f.values[0]), "C": math.ceil(df.temp_c.values[0])},
        "Dew Point": {"F": math.ceil(df.dew_point_f.values[0]), "C": math.ceil(df.dew_point_c.values[0])},
        "Humidity": math.ceil(df.humidity.values[0]),
        "Pressure": {"in": round(df.barometric_pressure_in.values[0],1), "mb": round(df.barometric_pressure_mb.values[0],1)},
        "Wind Speed": {"mph": round(df.wind_speed_mph.values[0],1), "kt": round(df.wind_speed_kt.values[0],1)},
        "Hourly Rain": {"in": round(df.hourly_rain_in.values[0],1), "cm": round(df.hourly_rain_cm.values[0],1)},
        "Wind Direction": wind_dir
    }

@project_bp.route("/wx")
def project3():
    db = Database()
    df = db.get_data()
    temp_f_fig = get_plot(df, 'temperature', 'f')
    temp_c_fig = get_plot(df, 'temperature', 'c')
    wind_mph_fig = get_plot(df, 'wind', 'mph')
    wind_kt_fig = get_plot(df, 'wind', 'kt')
    pressure_in_fig = get_plot(df, 'pressure', 'in')
    pressure_mb_fig = get_plot(df, 'pressure', 'mb')
    dew_point_f_fig = get_plot(df, 'dew point', 'f')
    dew_point_c_fig = get_plot(df, 'dew point', 'c')
    hourly_rain_in_fig = get_plot(df, 'hourly rain', 'in')
    hourly_rain_cm_fig = get_plot(df, 'hourly rain', 'cm')

    current_wx = get_current_weather(df)
    return render_template(
        "project3.html", title="\\\\Weather Station\\\\", title_img="weather.jpg",
        current_wx=current_wx,
        temp_f_fig=temp_f_fig,
        temp_c_fig=temp_c_fig,
        wind_mph_fig=wind_mph_fig,
        wind_kt_fig=wind_kt_fig,
        pressure_in_fig=pressure_in_fig,
        pressure_mb_fig=pressure_mb_fig,
        dew_point_f_fig=dew_point_f_fig,
        dew_point_c_fig=dew_point_c_fig,
        hourly_rain_in_fig=hourly_rain_in_fig,
        hourly_rain_cm_fig=hourly_rain_cm_fig
    )


def get_value(date, value_type):
    if value_type == 'prediction':
        key = f"{date.year}/{date.month}/{date.day}/prediction.txt"
    if value_type == 'actual':
        key = f"{date.year}/{date.month}/{date.day}/max_temp.txt"
    s3 = boto3.client('s3')
    try:
        obj = s3.get_object(Bucket="weather-bvmcode", Key=key)
    except ClientError:
        return None
    return round(float(obj['Body'].read().decode('utf-8')),1)


def date_range():
    utc_date = datetime.utcnow().replace(tzinfo=pytz.utc)
    dt_now = utc_date.astimezone(pytz.timezone('US/Eastern')).date()
    dt_14 = dt_now + timedelta(days=-15)
    dates = [dt_14]
    while True:
        if dt_14 >= dt_now:
            break
        else:
            dt_14 = dt_14 + timedelta(days=1)
            dates.append(dt_14)
    return dates


@api.route("/api/predictions")
class PredictionApi(Resource):
    # @cache.cached(timeout=1000, query_string=True)
    def get(self):
        dates = date_range()
        predictions = []
        actuals = []
        dates_updated = []
        for date in dates:
            pred = get_value(date, 'prediction')
            actual = get_value(date, 'actual')
            if pred is not None and actual is not None:
                dates_updated.append(date.strftime("%Y-%m-%d"))
                predictions.append(pred)
                actuals.append(actual)
        data = {
            "dates": dates_updated,
            "predictions": predictions,
            "actuals": actuals
        }
        return data


@project_bp.route("/predict")
def project4():
    utc_date = datetime.utcnow().replace(tzinfo=pytz.utc)
    dt_time = utc_date.astimezone(pytz.timezone('US/Eastern'))
    dt = dt_time.date()
    dt_prev = dt + timedelta(days=-1)
    prediction = get_value(dt, 'prediction')
    prediction_prev_day = get_value(dt_prev, 'prediction')
    actual_prev_day = get_value(dt_prev, 'actual')
    db = Database()
    current_temp = db.get_latest_temp()
    current_temp_max = db.get_current_max_temp(dt)

    message_prev_day = None
    difference = None
    last_updated_prev_day = datetime(dt.year, dt.month, dt.day, 0, 0, 0).strftime('%Y-%m-%d %I:%M %p EST')
    if prediction_prev_day is None or actual_prev_day is None:
        message_prev_day = "Yesterday's data is not available till after 9 AM EST."
        if (dt_time.hour == 9 and dt_time.minute>=15) or (dt_time.hour>9):
            message_prev_day = "Yesterday's data is not available due to missing data."
    else:
        difference = round(abs(prediction_prev_day - actual_prev_day),1)
   

    message = None
    last_updated = datetime(dt.year, dt.month, dt.day, 9, 0, 0).strftime('%Y-%m-%d %I:%M %p EST')
    if prediction is None:
        message = "Today's prediction is not available till after 9 AM EST."
        if (dt_time.hour == 9 and dt_time.minute>=15) or (dt_time.hour>9):
            message = "Today's prediction is not available due to missing data."
    return render_template(
        "project4.html", title="\\\\Max Temperature AI Prediction\\\\",
        title_img="weather.png",
        prediction=prediction,
        prediction_prev_day=prediction_prev_day,
        actual_prev_day=actual_prev_day,
        difference=difference,
        current_temperature=current_temp,
        last_updated=last_updated,
        last_updated_prev_day=last_updated_prev_day,
        message_prev_day=message_prev_day,
        current_temp_max=current_temp_max,
        message=message,
        today = dt.strftime("%m/%d/%Y"),
        prev_day = dt_prev.strftime("%m/%d/%Y")
    )


def get_latest_run(bucket):
    s3 = s3fs.S3FileSystem()
    path = f"{bucket}/gfs_images"
    latest_date = max([int(f.split("/")[2]) for f in s3.ls(path, refresh=True)])

client/app/resume/views.py
from flask import Blueprint, render_template

resume_bp = Blueprint("resume", __name__, url_prefix="/resume")


@resume_bp.route("/")
def resume():
    return render_template(
        "resume.html", title="\\\\resume\\\\", title_img="resume.jpg"
    )

client/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/bootstrap-5.1.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/fontawesome-free-6.1.1-web/css/all.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Chakra Petch' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet'>
    <script type="module" src="{{ url_for('static', filename='node_modules/chart.js/dist/chart.umd.js') }}" async></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <style>
      .navbar-nav .nav-item:not(:last-child) .nav-link {
    border-right: 1px solid #ffe873; /* Adjust color as desired */
    padding-right: 10px; /* Adds spacing to the right of the separator */
    margin-right: 10px; /* Adds spacing between the separator and the next item */
}
    </style>
    <nav class="navbar navbar-expand-lg navbar-light" >
        <a id="nav-title" class="navbar-brand" href="{{ url_for('home.home') }}">&nbsp;\\the_python_geek\\</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('home.home') }}"> Home </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('resume.resume') }}"> Resume </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('project.project3') }}"> My Wx Station </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="{{ url_for('project.project4') }}"> AI Wx Prediction </a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('project.project5') }}"> GFS Wx Models </a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0" id="nav-social-media">
            <li class="nav-item"></li>
            <a class="nav-link" target="_blank" href="https://www.linkedin.com/in/martbar"><i class="fa-brands fa-linkedin"></i></a>
          </li>
          <li class="nav-item"></li>
            <a class="nav-link" target="_blank" href="https://www.github.com/bvmcode"><i class="fa-brands fa-github"></i></a>
          </li>
          <li class="nav-item"></li>
            <a class="nav-link" target="_blank" href="https://medium.com/@the-python-geek"><i class="fa-brands fa-medium"></i></a>
          </li>
          </ul>
        </div>
      </nav>

      <div class="row" id="home-row">
        <div class="text-center mb-3 pb-3 pt-3" id="home-header">
            <div class="mt-3" id="home-img">
                <img class="img-fluid rounded-circle border border border-4" src="/static/images/{% block title_img %}{% endblock %}" alt="">
                <h1>{% block title_h1 %}{% endblock %}</h1>
            </div>
        </div>
    </div>
    <hr>
    <script src="/static/bootstrap-5.1.3-dist/js/bootstrap.bundle.js"></script>
    {% block content %}{% endblock %}
    <br>
    <br>
    <hr>
    <div>
      <div class="d-flex flex-row bd-highlight justify-content-center mb-3 home-list">
        <h5>Please visit any of my links below</h5>
    </div>
    <div class="d-flex flex-row bd-highlight justify-content-center mb-3 home-list">
        <div class="p-2 bd-highlight home-icon"><a target="_blank" href="https://www.linkedin.com/in/martbar"><i class="fa-brands fa-linkedin"></i></a></div>
        <div class="p-2 bd-highlight home-icon"><a target="_blank" href="https://www.github.com/bvmcode"><i class="fa-brands fa-github"></i></a></div>
        <div class="p-2 bd-highlight home-icon"><a target="_blank" href="https://medium.com/@the-python-geek"><i class="fa-brands fa-medium"></i></a></div>
    </div>
    </div>
    <br>
</body>
</html>

client/app/templates/home.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block title_h1 %}{{ title }}{% endblock %}
{% block title_img %}{{ title_img }}{% endblock %}

{% block content %}


<div class="container-fluid" id="home">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8 mb-3 mt-3" id="home-body">
            <p><span class="fs-1">H</span>ello, my name is Barry Martin. I live in south Jersey with my wonderful wife and two boys. I am a data and software 
            geek and have a passion for the science of meteorology. I find it extremely rewarding to use technology to capture weather data, 
            visualize, analyze and predict.
            I have many years of experience in the data analytics space performing complex analysis, automation development and software/data engineering.
        </p>
        <br>
        <p>If you like to reach out to me, please email me at <a href="mailto:bvmcode@thepythongeek.com?subject=Hello from your website!">bvmcode@thepythongeek.com</a>.</p>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
        <img src="{{ url_for('static', filename='images/me2.png') }}" style="width: 50%; height: auto; margin: 0 auto;" class="img-fluid">
    </div>
</div>
{% endblock %}

client/app/templates/project2.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block title_h1 %}{{ title }}{% endblock %}
{% block title_img %}{{ title_img }}{% endblock %}

{% block content %}
<div class="container" >
    
    <h1 class="mb-4">Data that Rocks!</h1>

    <h3 class="mb-2">Introduction</h3>
    <p>
        I decided to create a simple project that would marry my love for music and my addiction to Twitter and Spotify. So let us
        imagine that we work for a record company. A particular team in this company is really interested in 10 artists. They would 
        love to know the weekly trend of followers on both Spotify and Twitter. This would help inform their social media or
        marketing decisions. So they reached out to the analytics and engineering team to come up with an automated routine that would update 
        these figures on a nightly basis and provide a chart and update chart.
    </p>

    <p>
        So to tackle this I decided to use some AWS resources and this very web site. I figured I could keep this super light weight (no need for Airflow or a database here). 
        below is the design I went for. The code for this project is located <a href="https://github.com/bvmcode/thepythongeek_new/tree/master/follower_stats">here</a>.
        <img class="img-fluid" style="max-width:100%; margin: auto;" src="/static/images/proj_diagram.png" alt="">
    </p>


    <br>
    <h3 class="mb-2">Spotify and Twitter API</h3>
    <p> The first step was to create a python script that follows the basic logic below for each artist. Note that basic requests library was used 
        for getting Spotify data and <a href="https://www.tweepy.org/">tweepy</a> was used for accessing Twitter data.
    </p>
    <ul>
        <li>Get the Spotify artist object from the Spotify REST API</li>
        <li>From this object extract the number of Spotify followers</li>
        <li>Also from this artist object extract the Twitter ID</li>
        <li>Get the number of Twitter followers by using the Twitter ID against the Twitter REST API</li>
    </ul>
    <p>Then once all the data is captured, a json object is constructed that represents the data for the current date. The json object looks like: </p>
    <script src="https://gist.github.com/bvmcode/66a4ac8b632317725c1331bd9f011dfe.js"></script>
   <p>This encapsulates the core logic. As we will see in the next section, this will be wrapped into an AWS Lambda function so 
       that we can have a lightweight and modern way of accessing the needed data on a desired cadence.
   </p>

   <br>
   <h3 class="mb-2">AWS Resources</h3>
   <p>The logic from the previous section is encapsulated in the AWS Lambda function <a href="https://github.com/bvmcode/thepythongeek_new/blob/master/follower_stats/lambda_function.py">lambda_function.py</a>. 
    Additionally, the script <a href="https://github.com/bvmcode/thepythongeek_new/blob/master/follower_stats/create_lambda_resources.py">create_lambda_resources.py</a> is summarized well by it's 
    <i>main</i> function.

    <script src="https://gist.github.com/bvmcode/36520c68cc1f7e9f48ca1d2b16446f0a.js"></script>

    In other words, it does the following:
    <ul>
        <li>Create a zip file with the Lambda function python file and the site-packages dependencies</li>
        <li>Create AWS role to attach to the Lambda function in AWS so that we have write permissions to S3</li>
        <li>Create AWS Lambda function using the zip file and attach the AWS role</li>
        <li>Create an AWS Cloudwatch event to trigger the Lambda function daily</li>
    </ul>

    After running this script we have a Lambda function that is triggered daily by Cloudwatch in which json is delivered to our specicied S3 bucket.
</p>


<br>
<h3 class="mb-2">Application</h3>
<p>Now that we have data available in S3 we can use our <a href="https://flask.palletsprojects.com/en/2.2.x/">Flask</a> web application to display the data. The goal here is 
    to just present a plot that displays follower count data for the last 7 days. I made this real simple by creating a little REST API and utilized <a href="https://redis.io/">Redis</a> to 
    cache the data so that repeated access to the data is fast. I utilized the <a href="https://flask-restx.readthedocs.io/en/latest/">restx</a>
    library to create this endpoint.

    <script src="https://gist.github.com/bvmcode/98497e0458ef8a7e7d524da6eb725a0a.js"></script>

    <br>
    What this endpoint does is take in an artist name, fetches the last 7 days worth of data and reformats the data so that the keys are dates and the values
    are nested json of Spotify and Twitter follower values that looks like:
    <br>

    <script src="https://gist.github.com/bvmcode/4177de25d4e760ebafe3efb5b302cb71.js"></script>
   
    <br>
    And then we end up with is nicely formatted data that we can use to chart each artist's 7 day trend. Below shows both the HTML setup 
    (dropdown menu and available plot cavas) as well as the javascript that handles the plotting. 
    I used the <a href="https://www.chartjs.org/">chart.js</a> library here. We see here that the page loads by default with "Dream Theater" being
     selected and plotted. Based on the drop down selection the <i>getData</i> function is 
    called which then calls the <i>plot</i> function with artist as an argument. Data is fetched from the Flask API. The data is consumed and 
    reformatted so that two line plots (one Twitter and one Spotify) can be overlayed.
    
    <br>
    <script src="https://gist.github.com/bvmcode/4ae1c759ca25256ffc5ce02b2b204b56.js"></script>

</p>

    <br>
    <h3 class="mb-2">Data</h3>

    <p>Finally the team can view their data, which will auto-update nightly and provide the last 7 day trend!</p>
    <p>***Note - now that Twitter will be charging for access to their API, this project was brought down. Below is data for 1/1/2023-1/7/2023 read from AWS S3.</p>

    <div id="app">
        <label for="artists">Choose an artist:</label>
        <select autocomplete="off" name="artists" id="artists" onchange="getData.call(this, event)">
            <option value="Dream Theater">Dream Theater</option>
            <option value="Vola">Vola</option>
            <option value="Queensryche">Queensryche</option>
            <option value="Katatonia">Katatonia</option>
            <option value="Saint Asonia">Saint Asonia</option>
            <option value="Josh Garrels">Josh Garrels</option>
            <option value="Gunship">Gunship</option>
            <option value="Helloween">Helloween</option>
            <option value="Light The Torch">Light The Torch</option>
            <option value="Rend Collective">Rend Collective</option>
          </select>
        <canvas id="myChart"></canvas>
    </div>
</div>



<script>

async function plot(artist){
    let chartStatus = Chart.getChart("myChart"); // <canvas> id
    if (chartStatus != undefined) {
        chartStatus.destroy();
    }
    var url = "{{ url_for('project.artist_api', artist='ARTIST') }}".replace("ARTIST", artist)
    const response = await fetch(url);
    var data = await response.json();
    var spotify = [];
    var twitter = [];
    var dates = [];
    for (key in data){
        spotify.push(data[key]["spotify"])
        twitter.push(data[key]["twitter"])
        dates.push(key)
    }
    const config = {
        type: 'line',
        data:{
            labels: dates,
            datasets: [{
                label: 'Spotify',
                data: spotify,
                yAxisID: 'spotify'
            },
            {
                label: 'Twitter',
                data: twitter,
                yAxisID: 'twitter'
            }]
        },
        options: {
            scales: {
                spotify: {
                    position: 'left'
                        }, 
                twitter: {
                    position: 'right'
                        }
                }
            }
        };
 
        const myChart = new Chart("myChart", config)

}

window.addEventListener("load",function(){
    plot("Dream Theater"); 
},false);

function getData(event){
    event.preventDefault();
    var artist = this.options[this.selectedIndex].text
    plot(artist);
}

</script>

{% endblock %}

client/app/templates/project4.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block title_h1 %}{{ title }}{% endblock %}
{% block title_img %}{{ title_img }}{% endblock %}

{% block content %}
<div class="container">
    <h3 style="color: red">The predictions will be down for some time due to a change of physical address of my weather station as well as the govt shutdown where some data is not available.</h3>
    <br>
<div class="row">
    <div class="col-sm border-end text-center align-items-center">
        <h4 style="text-decoration: underline">About this model</h4>
        <p>I developed a machine learning model to predict the daily high temperature (°F) for my location in Atco, NJ. This page 
            displays the comparison between the model's prediction to the observed high temperature 
            from my <a href="{{ url_for('project.project3') }}">weather station</a>. 
            The model input is derived from surrounding NWS 12Z sounding data as well as 12Z observations 
            from my station.
            <br>
        </p>
        <p>Here is a <a href="https://medium.com/@weatherpy/machine-learning-for-hyperlocal-temperature-prediction-24388e34b8cd">blog</a> that goes into some technical detail about this project.</p>
    </div>
    <div class="col-sm border-end text-center align-items-center">
        <h4 style="text-decoration: underline">Previous Day <small>{{ prev_day }}</small></h4>
        {% if message_prev_day %}
            <p style="color:red;">{{ message_prev_day }}</p>
        {% else %}
            <p><small class="text-muted">updated {{ last_updated_prev_day }}</small></p>
        {% endif %}
        <p>PREDICTION: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% if (prediction_prev_day is not none) and (actual_prev_day is not none) %} 
                {{ prediction_prev_day }} °F
            {% else %}
            --
            {% endif %}
        </p>
        <p >ACTUAL: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% if (prediction_prev_day is not none) and (actual_prev_day is not none) %} 
                    {{ actual_prev_day }} °F
            {% else %}
            --
            {% endif %}
        </p>
        <p >DIFFERENCE: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% if (prediction_prev_day is not none) and (actual_prev_day is not none) %} 
                    {{ difference }} °F
            {% else %}
            --
            {% endif %}
        </p>
    </div>
    <div class="col-sm text-center align-items-center">
        <h4 style="text-decoration: underline">Today <small>{{ today }}</small></h4>
        {% if message %}
            <p style="color:red;">{{ message }}</p>
        {% else %}
            <p><small class="text-muted">updated {{ last_updated }}</small></p>
        {% endif %}
        <p>PREDICTION: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% if prediction is not none %} 
            {{ prediction }} °F
            {% else %}
            --
            {% endif %}
        </p>
        <p>HIGH TEMP TODAY: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {{ current_temp_max }} °F
        </p>
        <p>CURRENT TEMP: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {{ current_temperature }} °F
        </p>
    </div>
</div>

<br>
<br>

<div class="container">
    <h4>Two Week Daily High Temperatures ˚F</h4>
    <h5 class="text-muted">Predicted vs Observed</h5>
    <canvas id="myChart"></canvas>
</div>



</div>


<script>

    async function plot(){
        var url = "{{ url_for('project.prediction_api') }}"
        const response = await fetch(url);
        var data = await response.json();
        console.log(data)
        const config = {
            type: 'line',
            data:{
                labels: data['dates'],
                datasets: [{
                    label: 'Predicted',
                    data: data['predictions'],
                },
                {
                    label: 'Observed',
                    data: data['actuals'],
                }      
                ]
            },
            options: {
                responsive: true
            }
            };
            console.log(config)
            const myChart = new Chart("myChart", config)
    
    }
    
    window.addEventListener("load",function(){
        plot();
    },false);
    
    
    </script>

{% endblock %}